services:
  postgres:
    image: postgres:16-alpine
    container_name: doc_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: docdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d docdb"]
      interval: 3s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
